FROM tensorflow/tensorflow:2.4.1-gpu-jupyter

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./model_api.py /app/app.py
COPY ./model_serving_request.py /app

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
