FROM tensorflow/tensorflow:2.4.1-gpu-jupyter

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev ffmpeg sox

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/model/requirements.txt

WORKDIR /app/model

RUN pip install -r requirements.txt


ENTRYPOINT [ "python" ]

CMD [ "model_api.py" ]
